# Generated by Django 3.1.2 on 2020-11-25 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20201121_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='img',
            field=models.ImageField(height_field=1024, upload_to='blogImages', width_field=768),
        ),
    ]
