# Generated by Django 3.1.2 on 2020-11-25 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20201125_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='img',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='blogImages'),
        ),
    ]
